version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns: ["black", "isort", "mypy", "pylint", "pytest*", "vulture", "ruff"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
